# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Current Version
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    target-branch: release/0.6
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Etc/GMT"

  # Legacy Version
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    target-branch: release/0.5
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Etc/GMT"
